var OLSData={
	'service01':{group:'수문주제도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'UWL_WATERS_AS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'수역구분도',title:'수역구분도',version:'1.3.0',visible:false,opacity:0.5,prj:'EPSG:3857',zoomlevel:0,imageWidth:'58',imageHeight:'256'},	

	'service02':{group:'수자원관련시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_UW_OBSRVT_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'지하수위관측소',title:'지하수위관측소',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:0,imageWidth:'16',imageHeight:'16'},
	'service03':{group:'수자원관련시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_SW_PNTRTN_OBSRVT_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'해수침투관측소',title:'해수침투관측소',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},

	'service19':{group:'용천수활용시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_FNDST_RDCTN_FCLTY_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'미세먼지저감시설',title:'미세먼지저감시설',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service20':{group:'용천수활용시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_PUMP_CNTRL_DVC_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'펌프제어장치',title:'펌프제어장치',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service21':{group:'용천수활용시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_ROAD_WTRNG_DVC_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'도로살수장치',title:'도로살수장치',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service22':{group:'용천수활용시설',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'IP_D3_HLGRM_DVC_INFO_PS',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'3D홀로그램장치',title:'3D홀로그램장치',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	
	'service04':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_ADMB_AS',identify:'',style:'',name:'행정구역경계',title:'행정구역경계',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:0,imageWidth:'16',imageHeight:'16'},
	'service05':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_BADM_AS',identify:'',style:'',name:'법정동읍면동리',title:'법정동읍면동리',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:0,imageWidth:'16',imageHeight:'16'},
	'service06':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'LSMD_CONT_LDREG_50K',identify:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WFSServer?VERSION=1.1.0&SERVICE=WFS&REQUEST=GetFeature',style:'',name:'지적도',title:'지적도',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:15,imageWidth:'16',imageHeight:'16'},
	'service07':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'TL_SPBD_BULD_PROJECT_MERGE_NEW',identify:'',style:'',name:'건물_새주소',title:'건물_새주소',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:15,imageWidth:'16',imageHeight:'16'},
	'service08':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_ELEV_LS',identify:'',style:'',name:'등고',title:'등고',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:15,imageWidth:'16',imageHeight:'16'},
	'service09':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_RIVR_LS',identify:'',style:'',name:'하천',title:'하천',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service10':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_KUKG_AS',identify:'',style:'',name:'국공유지',title:'국공유지',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'46',imageHeight:'32'},
	'service11':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_BLDG_AS',identify:'',style:'',name:'건물_수치지형도',title:'건물_수치지형도',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service12':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_RBLN_LS',identify:'',style:'',name:'도로_수치지형도',title:'도로_수치지형도',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service13':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_LABL_PS',identify:'',style:'',name:'주기',title:'주기',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service14':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_CMTY_PS',identify:'',style:'',name:'묘지',title:'묘지',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service15':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'JJUIS.BML_CSLN_LS_5K',identify:'',style:'',name:'해안선',title:'해안선',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service16':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'BML_ADMB_LS',identify:'',style:'',name:'행정구역경계선',title:'행정구역경계선',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service17':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'TL_SPRD_MANAGE_PROJECT_NEW',identify:'',style:'',name:'중심선(새주소)',title:'중심선(새주소)',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
	'service18':{group:'기본도',url:'https://gis.jeju.go.kr/arcgis/services/JJGWIMS/JJGWIMS/MapServer/WMSServer?1',service:'IMG',groupName:'',layer:'TL_SPRD_RW',identify:'',style:'',name:'실폭도로',title:'실폭도로',version:'1.3.0',visible:false,opacity:1,prj:'EPSG:3857',zoomlevel:10,imageWidth:'16',imageHeight:'16'},
};